### ISSUE TITLE
Populate week number when scraping player stats

### ISSUE THREAD

**Issue by keylime503** [rmayf/CollegeFootballChallenge#1]
week = -1 # TODO

**Comment by rmayf** [comment]
We can have a cronjob that runs every Monday and updates the currentWeek field in the Season table
( don't know if you saw the inline comment )

**Comment by keylime503** [comment]
So this is actually already fixed:

`    def __init__( self, gameId ):
        try:                                                                                                                                                                                                       
            game = Game.objects.get( gameId=gameId )
            awayTeamId = game.opponent.teamId
            homeTeamId = game.team.teamId
            self.week = game.week
        except Game.DoesNotExist:
            # TODO: handle more gracefully
            awayTeamId = -1
            homeTeamId = -1
            self.week = -1`

**Comment by keylime503** [comment]
Right now we always hit the except since we're testing with a 2015 gameId (2016 gameIds won't exist till after the game).
