### ISSUE TITLE
script to dump the database nightly and save the backup somewhere

### ISSUE THREAD

**Issue by rmayf** [rmayf/CollegeFootballChallenge#16]

**Comment by rmayf** [comment]
file to backup is: /home/home/CollegeFootballChallenge/django/prod.sqlite3

**Comment by brockm1** [comment]
I created an Rsync script to back up the prod.sqlite3 database.  The script is set to run every day at midnight.  I will test and make sure the script is backing up correctly.

**Comment by rmayf** [comment]
Seems like this is working. hopefully we will never have to use it to recover! Thanks Brock
