### ISSUE TITLE
Switching tabs from default of 'Quarterbacks' to another position is a no-op

### ISSUE THREAD

**Issue by keylime503** [rmayf/CollegeFootballChallenge#32]
Browser says: (index):291 Uncaught ReferenceError: selectPos is not defined

**Comment by rmayf** [comment]
The javascript source isn't being delivered to the client after changing DEBUG = FALSE on prod.  Need to investigate

**Comment by rmayf** [comment]
[Stackoverflow](http://stackoverflow.com/questions/5836674/why-does-debug-false-setting-make-my-django-static-files-access-fail)

`manage.py runserver --insecure` solves the issue
